Feature/task 1 - communication/review
profick/omp-bot pull request #1
Opened 2021-10-18 20:37 UTC by profick

Implementation of Task 1 https://github.com/ozonmp/omp-docs.

Domain/Subdomain: Communication/Review

2021-10-19 22:00 UTC, Vulp1x requested changes
Аналогично надо сделать для Commander

2021-10-19 22:00 UTC, Vulp1x commented on internal/service/communication/review/service.go
> +type ReviewService interface {
Стоит переименовать в Service (смотри тред  https://route256.slack.com/archives/C02F8NN6WKV/p1634640741130400)

2021-10-19 22:00 UTC, Vulp1x commented on internal/service/communication/review/service.go
> +type CommunicationReviewService struct {
стоит сделать  неэкспортируемыми, так пользователи смогут пользоваться твоей структурой только через интерфейс.

2021-10-19 22:00 UTC, Vulp1x commented on internal/service/communication/review/service.go
> +func NewCommunicationReviewService() *CommunicationReviewService {
Возвращай интерфейс `Service` (сейчас это интерфейс `ReviewService`). То есть будет `func NewCommunicationReviewService() Service{`

2021-10-19 23:55 UTC, profick commented
Долго вникая в тред в слаке осознал, что рецепт - это лишь рекомендации, как можно решить задание, но не требования.
Решил, что лучше тогда пойти как можно ближе к go way.
Во многом опираясь на вторую лекцию по интерфейсам (которую проводил Даниил Подольский) взял за основное правило, что интерфейсы должны быть декларированы там, где они используются, а не там, где они реализовываются.

Таким образом, внесены следующие изменения: 
1) `internal/service/communication/review`  теперь содержит конструктор `NewService`, который возвращает указатель на структуру `review.Service` [ссылка на код](https://github.com/profick/omp-bot/pull/1/files#diff-ff4ae680c28a8ef728e29938cad23010154c6f3a5d80b6743a7f251d5c3b6852R11-R21)
2) `internal/app/commands/communication/review` теперь содержит структуру `SubCommander` вместо `Commander` (на мой взгляд так яснее, за какой ресурс отвечает коммандер - domain/subdomain). Также пакет содержит декларацию интерфейса `SubCommanderService`, который реализован в первом пункте. Все методы обработки комманд/коллбэков теперь приватные, т.к. используются только внутри пакета. Публичные только 2 метода `HandleCallback` и `HandleCommand` для того, чтобы реализовывать интерфейс `communication.subCommander`. [ссылка на код](https://github.com/profick/omp-bot/pull/1/files#diff-1a3298dee5ea4a2a90051e72ce17f435f1bf3b013aac615f934087042ded5c0cR11-R29)
3) `internal/app/commands/communication` содержит декларацию интерфейса `subCommander`. Интерфейс приватный, т.к. используется только в рамках пакета. Аналогично предыдущим пунктам, содержит конструктор, возвращающий указатель на структуру, в данном случае `communication.Commander` [ссылка на код](https://github.com/profick/omp-bot/pull/1/files#diff-110f45265d2dd398b7a9190ced3ef6669729b60ff7d1318809109ea34bebd985R12-R28)

Сделано по аналогии с тем, как `router` декларирует интерфейс `router.Commander`, который затем реализуется в `communication.Commander`.

2021-10-19 23:57 UTC, profick commented on internal/service/communication/review/service.go
> +type ReviewService interface {
Переименовал, но теперь это структура. Интерфейс перенесён в место, где он будет использоваться.

[ссылка на код](https://github.com/profick/omp-bot/pull/1/files#diff-ff4ae680c28a8ef728e29938cad23010154c6f3a5d80b6743a7f251d5c3b6852R11-R21)

Подробно отписался в https://github.com/profick/omp-bot/pull/1#issuecomment-947192194

2021-10-20 00:03 UTC, profick commented on internal/service/communication/review/service.go
> +type CommunicationReviewService struct {
Изменил структуру кода, теперь интерфейс перенёсен в место, где он используется. В качестве реализации будет возвращаться структура. Не уверен, не имеет ли каких-то негативных последствий возвращение неэкспортируемой структуры из конструктора в данном случае. 

[ссылка на код](https://github.com/profick/omp-bot/pull/1/files#diff-ff4ae680c28a8ef728e29938cad23010154c6f3a5d80b6743a7f251d5c3b6852R11-R21)

Подробно отписался в https://github.com/profick/omp-bot/pull/1#issuecomment-947192194

2021-10-20 00:07 UTC, profick commented on internal/service/communication/review/service.go
> +func NewCommunicationReviewService() *CommunicationReviewService {
Подробно отписался в https://github.com/profick/omp-bot/pull/1#issuecomment-947192194

2021-10-20 22:31 UTC, Vulp1x approved these changes

2021-12-01 19:21 UTC, merged